---
 - hosts: all
   tasks:

     - name: Install software-properties-common
       apt:
        name: software-properties-common
        state: present

     - name: Add apt key
       command: apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8

     - name: Add MariaDB Repo
      apt_repository:
        filename: MariaDB-10.3
        repo: deb [arch=amd64,arm64,ppc64el] http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.3/ubuntu bionic main
        state: present

     - name: Install MariaDB Packages
      apt: name={{item}} state=installed default_release=trusty update_cache=yes
      with_items:
        - mariadb-client
        - mariadb-common
        - mariadb-server

     - name: Create a symbolic link
       ansible.builtin.file:
                 src: ./file/mariadb.list
                 dest: /etc/apt/sources.list.d/
                 owner: root
                 group: root
                 mod: 644
                 state: file

     - name: Update repositories
       apt:
         update_cache: yes

     - name: Setting up root credentials
       mysql_user:
         name: root
         password: "{{}}"
         login_user: root
         login_password: "{{mysql}}"
         host: localhost
         login_unix_socket: /var/lib/mysql/mysql.sock
         priv: '*.*:ALL,GRANT'
         check_implicit_admin: true
         state: present

